[2024-02-26 15:34:01] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:06] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:06] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 352865d3401a4b5b 127.0.0.1:20130 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:06] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 352865d3401a4b5b 127.0.0.1:63070 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:11] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:16] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:21] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:26] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:31] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:36] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:37] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 352865d3401a4b5b 127.0.0.1:63189 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:37] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 352865d3401a4b5b 127.0.0.1:20130 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:41] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:46] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:51] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:56] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
