[2024-02-26 15:31:12] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn aa9452e8ff26a194 127.0.0.1:62025 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:31:12] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn aa9452e8ff26a194 127.0.0.1:20133 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:31:42] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn aa9452e8ff26a194 127.0.0.1:20133 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:31:42] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn aa9452e8ff26a194 127.0.0.1:62265 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:31:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:31:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:31:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:31:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
