[2024-02-26 15:34:04] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:09] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:14] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 1b469003b449ae80 127.0.0.1:63099 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 1b469003b449ae80 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:19] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:24] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:29] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:34] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:39] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:46] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 1b469003b449ae80 127.0.0.1:63225 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:46] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 1b469003b449ae80 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
