[2024-02-26 15:31:10] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 1b469003b449ae80 127.0.0.1:61997 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:31:10] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 1b469003b449ae80 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:31:12] [warning] server.go:553 p3Chain/p2p/server.(*Server).encHandshakeChecks 进行加密handshake: 节点已经与本机建立了连接

[2024-02-26 15:31:12] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 9c932476cf018f45 127.0.0.1:62019 failed checkpoint posthandshake: Already connected
[2024-02-26 15:31:40] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 1b469003b449ae80 127.0.0.1:62260 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:31:40] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 1b469003b449ae80 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:31:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:31:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:31:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:31:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
