[2024-03-28 17:53:01] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-03-28 17:53:06] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-03-28 17:53:11] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-03-28 17:53:16] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-03-28 17:53:21] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-03-28 17:53:23] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn ea8956dc272cf532 127.0.0.1:58667 failed checkpoint posthandshake: Connected to self
[2024-03-28 17:53:23] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn ea8956dc272cf532 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2024-03-28 17:53:26] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-03-28 17:53:31] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-03-28 17:53:36] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-03-28 17:53:41] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-03-28 17:53:43] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:43] [warning] synchronization.go:209 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (ff26944f9dc7e38d41eb78eaa079a843d2c196726bf7d3fae388bfb7adb5ca3890413fadc4cb31001760f33b746a5afaee0f2c7161611c63ec06a358a86fdfba), err:EOF

[2024-03-28 17:53:43] [warning] peer.go:207 p3Chain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2024-03-28 17:53:43] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:43] [error] dial.go:216 p3Chain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20135: connect: connection refused
[2024-03-28 17:53:44] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:44] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:44] [warning] synchronization.go:209 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (860bfc8357f1a84136a799c0b9ac4eb04e074213b23352068d54456af15f8ba795b6a9d598d5232f092c3cb269c84da0525c658509d1ec6d7b0ad41e0ff9e0c3), err:EOF

[2024-03-28 17:53:44] [warning] peer.go:207 p3Chain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2024-03-28 17:53:44] [error] dial.go:216 p3Chain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20133: connect: connection refused
[2024-03-28 17:53:44] [warning] synchronization.go:209 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (dd9104160b7eafea2df255a402b534702d19d616279f5846f840507dbd56ce2aa6814df2c19349e005c15bfc2729811ef40d16aaa8dbabedfc7c20618274ec4c), err:EOF

[2024-03-28 17:53:44] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:44] [warning] peer.go:207 p3Chain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2024-03-28 17:53:44] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:44] [error] dial.go:216 p3Chain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20134: connect: connection refused
[2024-03-28 17:53:44] [warning] peer.go:207 p3Chain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2024-03-28 17:53:44] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:44] [error] dial.go:216 p3Chain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20136: connect: connection refused
[2024-03-28 17:53:44] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:44] [warning] synchronization.go:209 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (e854f680f9662f50a8013ccef2d64bba26973b834c0fc34bad67ec4e66c4e5130e7ebed65cc46a4ceeafe0a6b4ed3244d529032581cd6a4b5dafdcac0bb1ab93), err:EOF

[2024-03-28 17:53:44] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:protocol returned

[2024-03-28 17:53:45] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:protocol returned

[2024-03-28 17:53:45] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:45] [warning] peer.go:207 p3Chain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2024-03-28 17:53:45] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-03-28 17:53:45] [warning] synchronization.go:209 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (6552e02e745ce2e1ee7f382efa18769770fc9bdc5092c9f86bd3dffc87b2eed6f20fcd4a322f4f040c8d0e34a4acf9ca674c2fb1db6090a87fb9bc44467356ad), err:EOF

[2024-03-28 17:53:45] [error] dial.go:216 p3Chain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20132: connect: connection refused
