[2024-02-26 15:35:04] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:35:09] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:35:14] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:35:19] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-02-26 15:35:19] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-02-26 15:35:19] [warning] peer.go:207 p3Chain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2024-02-26 15:35:19] [error] dial.go:216 p3Chain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20130: connect: connection refused
[2024-02-26 15:35:19] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:35:19] [warning] synchronization.go:209 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (ea52714e4fd1a6875f02248962351555ab0a232ef8eaf938479d775ff4febf40017c0d010261cf4710af0c4f535a397504010b0e0da37875c3a4441072c9f5d9), err:EOF

[2024-02-26 15:35:19] [warning] peer.go:207 p3Chain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2024-02-26 15:35:19] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-02-26 15:35:19] [error] dial.go:216 p3Chain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20136: connect: connection refused
[2024-02-26 15:35:19] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-02-26 15:35:20] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn a40fd9471091bc7f 127.0.0.1:63377 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:35:20] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn a40fd9471091bc7f 127.0.0.1:20135 failed checkpoint posthandshake: Connected to self
