[2024-03-28 17:51:48] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn dd9104160b7eafea 127.0.0.1:58185 failed checkpoint posthandshake: Connected to self
[2024-03-28 17:51:48] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn dd9104160b7eafea 127.0.0.1:20134 failed checkpoint posthandshake: Connected to self
[2024-03-28 17:51:48] [warning] server.go:553 p3Chain/p2p/server.(*Server).encHandshakeChecks 进行加密handshake: 节点已经与本机建立了连接

[2024-03-28 17:51:48] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 860bfc8357f1a841 127.0.0.1:58192 failed checkpoint posthandshake: Already connected
[2024-03-28 17:51:48] [warning] server.go:553 p3Chain/p2p/server.(*Server).encHandshakeChecks 进行加密handshake: 节点已经与本机建立了连接

[2024-03-28 17:51:48] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn ea8956dc272cf532 127.0.0.1:58195 failed checkpoint posthandshake: Already connected
